### ISSUE TITLE
Default room for venue picker

### ISSUE THREAD

**Issue by ocapehorn** [rgb-monster/confirmed.show#25]
Change default name from Room 1 to 'Performance space' 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/1185068/211582833-e4b74979-9b7f-43fe-9337-c5050c2fede0.png">

**Comment by tstriker** [comment]
can we have something shorter? otherwise we'll end up with lots of "performance space@venue name"

**Comment by tstriker** [comment]
and what do i call room 2?

**Comment by tstriker** [comment]
what about "Space 1"?

**Comment by ocapehorn** [comment]
I've noticed that there are more venues than not that have the venue name synonymous with the performance space. The elephant & wheelbarrow is a decent example. Bar 50, 3 sisters and the like are possibly the exception and not the rule. Space is better than room however.

**Comment by tstriker** [comment]
feexed. and also did the single-room-no-room thing
