### ISSUE TITLE
Add city in act profile 

### ISSUE THREAD

**Issue by ocapehorn** [rgb-monster/confirmed.show#27]
In which city are you based? 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1185068/212377653-bdc3e1c9-8788-4077-8f86-516ab14e51bd.png">

May be used to differentiate acts who live in e.g. Barcelona and who are just visiting.

**Comment by ocapehorn** [comment]
This can of course be done with a tag, but we'd want acts to self-select then map that to a tag.

**Comment by tstriker** [comment]
i was rather thinking a searchable text entry, as it's not just city, but also country and, if the city is big enough, area in the city etc etc

**Comment by ocapehorn** [comment]
Yes you might be right. This approach does rely a bit more on the quality
of the act’s input but probably better long term.
